# Generated by Django 4.1.2 on 2022-12-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(max_length=10)),
                ('author_username', models.CharField(max_length=150, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('upvotes', models.IntegerField()),
                ('viewers', models.IntegerField()),
                ('comments_count', models.IntegerField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_page.profile')),
            ],
        ),
    ]
