<<<<<<< Updated upstream
# Generated by Django 4.1.2 on 2022-11-02 14:35
=======
# Generated by Django 4.1.2 on 2022-12-10 15:04
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_expert', models.BooleanField(default=False, null=True)),
                ('first_name', models.CharField(default=None, max_length=20, null=True)),
                ('last_name', models.CharField(default=None, max_length=20, null=True)),
                ('email', models.EmailField(default=None, max_length=254, null=True, unique=True)),
                ('birth_date', models.DateField(default=None, null=True)),
                ('occupation', models.CharField(default=None, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
