# Generated by Django 4.1.2 on 2022-11-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdukasiComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('content', models.TextField(max_length=255)),
                ('upvotes', models.IntegerField()),
                ('saved', models.IntegerField()),
            ],
        ),
    ]
