# Generated by Django 4.1.2 on 2022-10-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edukasi_item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edukasicomment',
            name='saved',
        ),
        migrations.AlterField(
            model_name='edukasicomment',
            name='content',
            field=models.TextField(),
        ),
    ]
