# Generated by Django 4.1.2 on 2022-10-29 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_remove_post_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumOpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.post')),
                ('upvoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
